contact_links:
  - name: (Sample) Feature request
    url: ../../../discussions/categories/ideas
    about: Share ideas for new features
  - name: (Sample) Ask a question
    url: ../../../discussions/categories/q-a
    about: Ask questions and discuss with other community members
